<?php
session_start();
require_once 'admin_access.php';
require_once '../config/database.php';
require_once 'ownership_transfer_common.php';
require_once 'homeowner_activity_logger.php';
requireAccess('homeowner_management');

if (!function_exists('esc')) {
    function esc($v): string {
        return htmlspecialchars(
            (string)$v,
            ENT_QUOTES,
            'UTF-8'
        );
    }
}

function redirect_with_message(string $type, string $message, string $location = 'ho_register.php'){
  $_SESSION['flash_type'] = $type;
  $_SESSION['flash_message'] = $message;
  header("Location: " . $location);
  exit;
}
function normalizePhase($phase){
    $phase = trim((string)$phase);

    $allowed = [
        'Phase 1',
        'Phase 2',
        'Phase 3'
    ];

    return in_array(
        $phase,
        $allowed,
        true
    )
        ? $phase
        : '';
}

/*
|--------------------------------------------------------------------------
| Secure document upload
|--------------------------------------------------------------------------
*/
function saveRegistrationDocument(
    array $file,
    string $documentType
): string {

    /*
     * Allowed document types used in the filename.
     */
    if (
        !in_array(
            $documentType,
            ['id', 'proof'],
            true
        )
    ) {
        throw new RuntimeException(
            'Invalid document type.'
        );
    }


    /*
     * Make sure PHP received a normal upload.
     */
    if (
        !isset($file['error']) ||
        is_array($file['error'])
    ) {
        throw new RuntimeException(
            'Invalid uploaded file.'
        );
    }


    switch ($file['error']) {

        case UPLOAD_ERR_OK:
            break;

        case UPLOAD_ERR_NO_FILE:
            throw new RuntimeException(
                'Please select the required document.'
            );

        case UPLOAD_ERR_INI_SIZE:
        case UPLOAD_ERR_FORM_SIZE:
            throw new RuntimeException(
                'The uploaded document is too large.'
            );

        default:
            throw new RuntimeException(
                'The document upload failed.'
            );
    }


    /*
     * Maximum file size: 5 MB.
     */
    $maxSize =
        5 * 1024 * 1024;


    if (
        (int)($file['size'] ?? 0) <= 0 ||
        (int)$file['size'] > $maxSize
    ) {

        throw new RuntimeException(
            'Documents must be 5 MB or smaller.'
        );
    }


    $tmpName =
        (string)($file['tmp_name'] ?? '');


    if (
        $tmpName === '' ||
        !is_uploaded_file($tmpName)
    ) {

        throw new RuntimeException(
            'Invalid uploaded document.'
        );
    }


    /*
     * Detect the REAL file MIME type.
     * Never trust $_FILES["type"].
     */
    $finfo =
        new finfo(
            FILEINFO_MIME_TYPE
        );


    $mimeType =
        $finfo->file(
            $tmpName
        );


    $allowedTypes = [

        'image/jpeg' =>
            'jpg',

        'image/png' =>
            'png',

        'application/pdf' =>
            'pdf'
    ];


    if (
        !isset(
            $allowedTypes[
                $mimeType
            ]
        )
    ) {

        throw new RuntimeException(
            'Only JPG, PNG, and PDF documents are allowed.'
        );
    }


    $extension =
        $allowedTypes[
            $mimeType
        ];


    /*
     * Project-root uploads directory.
     */
    $uploadDirFs =
        dirname(__DIR__) .
        DIRECTORY_SEPARATOR .
        'uploads' .
        DIRECTORY_SEPARATOR;


    if (
        !is_dir($uploadDirFs) &&
        !mkdir(
            $uploadDirFs,
            0755,
            true
        )
    ) {

        throw new RuntimeException(
            'Unable to create upload directory.'
        );
    }


    /*
     * Random server-generated filename.
     *
     * Example:
     * 28ba8f...._id.jpg
     */
    $fileName =
        bin2hex(
            random_bytes(16)
        ) .
        '_' .
        $documentType .
        '.' .
        $extension;


    $filePath =
        $uploadDirFs .
        $fileName;


    if (
        !move_uploaded_file(
            $tmpName,
            $filePath
        )
    ) {

        throw new RuntimeException(
            'Failed to save uploaded document.'
        );
    }


    /*
     * Path stored in database.
     */
    return
        'uploads/' .
        $fileName;
}


/*
|--------------------------------------------------------------------------
| Verify a document carried from Step 1 to Step 2
|--------------------------------------------------------------------------
*/
function validRegistrationDocument(
    string $dbPath,
    string $documentType
): bool {

    if (
        !in_array(
            $documentType,
            ['id', 'proof'],
            true
        )
    ) {
        return false;
    }


    /*
     * Only accept filenames generated by
     * saveRegistrationDocument().
     */
    $pattern =
        '~^uploads/' .
        '[a-f0-9]{32}_' .
        preg_quote(
            $documentType,
            '~'
        ) .
        '\.(?:jpg|png|pdf)$~D';


    if (
        !preg_match(
            $pattern,
            $dbPath
        )
    ) {

        return false;
    }


    $fullPath =
        dirname(__DIR__) .
        DIRECTORY_SEPARATOR .
        str_replace(
            '/',
            DIRECTORY_SEPARATOR,
            $dbPath
        );


    return is_file(
        $fullPath
    );
}

/*
|--------------------------------------------------------------------------
| Official South Meridian Block / Lot Mapping
|--------------------------------------------------------------------------
*/
function loadSouthMeridianLocations(): array
{
    $path =
        __DIR__ .
        '/southmeri_block_lot_mapping.json';

    if (!is_readable($path)) {
        throw new RuntimeException(
            'South Meridian Block/Lot mapping file was not found.'
        );
    }

    $decoded =
        json_decode(
            (string) file_get_contents($path),
            true
        );

    if (!is_array($decoded)) {
        throw new RuntimeException(
            'South Meridian Block/Lot mapping file is invalid.'
        );
    }


    $pageWidthEmu =
        8.5 * 914400;

    $pageHeightEmu =
        11 * 914400;

    $pageMarginEmu =
        914400;

    $markerCenterOffsetEmu =
        90000;


    $locations = [];


    foreach ($decoded as $item) {

        $block =
            (int)($item['block'] ?? 0);

        $lot =
            (int)($item['lot'] ?? 0);


        if (
            $block <= 0 ||
            $lot <= 0
        ) {
            continue;
        }


        $xEmu =
            (float)($item['x_emu'] ?? 0);

        $yEmu =
            (float)($item['y_emu'] ?? 0);


        $mapX =
            (int) round(
                (
                    (
                        $pageMarginEmu +
                        $xEmu +
                        $markerCenterOffsetEmu
                    )
                    /
                    $pageWidthEmu
                )
                * 2550
            );


        $mapY =
            (int) round(
                (
                    (
                        $pageMarginEmu +
                        $yEmu +
                        $markerCenterOffsetEmu
                    )
                    /
                    $pageHeightEmu
                )
                * 3300
            );


        $locations[
            $block . ':' . $lot
        ] = [
            'block' =>
                $block,

            'lot' =>
                $lot,

            'street' =>
                trim(
                    (string)(
                        $item['street'] ?? ''
                    )
                ),

            'map_x' =>
                $mapX,

            'map_y' =>
                $mapY
        ];
    }


    return $locations;
}

function phase_prefix(string $phase): string {
  $n = (int) filter_var($phase, FILTER_SANITIZE_NUMBER_INT);
  return $n > 0 ? ('P'.$n) : 'P';
}


if (empty($_SESSION['admin_id']) || empty($_SESSION['admin_role']) ||
    !in_array($_SESSION['admin_role'], ['admin','superadmin'], true)) {
  $_SESSION['flash_type'] = 'danger';
  $_SESSION['flash_message'] = 'Access denied. Please login as admin.';
  header("Location: index.php");
  exit();
}

mysqli_report(MYSQLI_REPORT_ERROR | MYSQLI_REPORT_STRICT);


// admin info from DB
$admin_id = (int)$_SESSION['admin_id'];
$stmt = $conn->prepare("SELECT phase, role FROM admins WHERE id=? LIMIT 1");
$stmt->bind_param("i", $admin_id);
$stmt->execute();
$admin = $stmt->get_result()->fetch_assoc();
$stmt->close();

$admin_phase = $admin['phase'] ?? '';
$admin_role  = $admin['role'] ?? '';
$isHOSection = true;

if (!isset($permissions) || !is_array($permissions)) {
  $permissions = [];
}

/*
 * Load official subdivision locations once.
 */
try {

    $southMeridianLocations =
        loadSouthMeridianLocations();

} catch (Throwable $e) {

    redirect_with_message(
        'danger',
        $e->getMessage()
    );
}

// ---- STEP 2: Final submission with confirmed Block/Lot location ----
if (isset($_POST['submit_location'])) {
  try {
$first_name =
    trim(
        (string)(
            $_POST['first_name'] ?? ''
        )
    );

$middle_name =
    trim(
        (string)(
            $_POST['middle_name'] ?? ''
        )
    );

$last_name =
    trim(
        (string)(
            $_POST['last_name'] ?? ''
        )
    );

$contact_number =
    trim(
        (string)(
            $_POST['contact_number'] ?? ''
        )
    );

$email =
    trim(
        (string)(
            $_POST['email'] ?? ''
        )
    );


/*
|--------------------------------------------------------------------------
| Phase
|--------------------------------------------------------------------------
|
| Normal admins are locked to their assigned phase.
| Superadmin may choose Phase 1, 2 or 3.
|
*/

if ($admin_role === 'superadmin') {

    $phase =
        normalizePhase(
            $_POST['phase'] ?? ''
        );

} else {

    $phase =
        normalizePhase(
            $admin_phase
        );
}


/*
|--------------------------------------------------------------------------
| Block / Lot
|--------------------------------------------------------------------------
*/

$block =
    (int)(
        $_POST['block'] ?? 0
    );

$lot =
    (int)(
        $_POST['lot'] ?? 0
    );


/*
|--------------------------------------------------------------------------
| Required Fields
|--------------------------------------------------------------------------
*/

if (
    $first_name === '' ||
    $last_name === '' ||
    $contact_number === '' ||
    $email === '' ||
    $phase === '' ||
    $block <= 0 ||
    $lot <= 0
) {

    redirect_with_message(
        'danger',
        'Missing required fields.'
    );
}


/*
|--------------------------------------------------------------------------
| Verify Block / Lot against official South Meridian map
|--------------------------------------------------------------------------
*/

$locationKey =
    $block . ':' . $lot;


if (
    !isset(
        $southMeridianLocations[
            $locationKey
        ]
    )
) {

    redirect_with_message(
        'danger',
        "Block {$block}, Lot {$lot} is not a valid South Meridian property."
    );
}


$location =
    $southMeridianLocations[
        $locationKey
    ];


/*
|--------------------------------------------------------------------------
| Canonical Location Values
|--------------------------------------------------------------------------
|
| These values come from the official subdivision mapping.
| Do NOT accept them directly from the browser.
|
*/

$street =
    trim(
        (string)(
            $location['street'] ?? ''
        )
    );

$map_x =
    (int)(
        $location['map_x'] ?? 0
    );

$map_y =
    (int)(
        $location['map_y'] ?? 0
    );


$house_lot_number =
    "Block {$block} Lot {$lot}";


$barangay =
    'Salitran IV';

$city_municipality =
    'Dasmarinas City';

$province =
    'Cavite';

$region =
    'CALABARZON';

$zip_code =
    '4114';

$country =
    'Philippines';


/*
|--------------------------------------------------------------------------
| Validate account fields
|--------------------------------------------------------------------------
*/

if (
    !filter_var(
        $email,
        FILTER_VALIDATE_EMAIL
    )
) {

    redirect_with_message(
        'danger',
        'Invalid email address.'
    );
}


if (
    strlen(
        $contact_number
    ) > 15
) {

    redirect_with_message(
        'danger',
        'Contact number must not exceed 15 characters.'
    );
}




/*
|--------------------------------------------------------------------------
| Documents carried from Step 1
|--------------------------------------------------------------------------
*/

$valid_id_path =
    trim(
        (string)(
            $_POST['valid_id_tmp'] ?? ''
        )
    );

$proof_path =
    trim(
        (string)(
            $_POST['proof_tmp'] ?? ''
        )
    );


if (
    !validRegistrationDocument(
        $valid_id_path,
        'id'
    )
    ||
    !validRegistrationDocument(
        $proof_path,
        'proof'
    )
) {

    redirect_with_message(
        'danger',
        'The uploaded documents are missing or invalid. Please restart the registration.'
    );
}
    // check duplicate email first
    $stmtCheck = $conn->prepare("SELECT id FROM homeowners WHERE email = ? LIMIT 1");
    $stmtCheck->bind_param("s", $email);
    $stmtCheck->execute();
    $exists = $stmtCheck->get_result()->fetch_assoc();
    $stmtCheck->close();

    if ($exists) {
      redirect_with_message('danger', 'Email already exists.');
    }

    /*
     * A different person/email using a property that already has an
     * approved homeowner is NOT rejected here. Save the registration as
     * Pending, then require the ownership-transfer verification flow.
     */
    $possibleTransferOwner = otFindApprovedPropertyOwner(
        $conn,
        [
            'phase' => $phase,
            'block' => $block,
            'lot' => $lot,
            'house_lot_number' => $house_lot_number,
            'email' => $email
        ]
    );

    // assign admin based on phase
    $assigned_admin_id = null;
    $stmtAdmin = $conn->prepare("
      SELECT id
      FROM admins
      WHERE phase = ?
      ORDER BY CASE WHEN position = 'President' THEN 0 ELSE 1 END, id ASC
      LIMIT 1
    ");
    $stmtAdmin->bind_param("s", $phase);
    $stmtAdmin->execute();
    $resAdmin = $stmtAdmin->get_result()->fetch_assoc();
    $stmtAdmin->close();

    if ($resAdmin && isset($resAdmin['id'])) {
      $assigned_admin_id = (int)$resAdmin['id'];
    }

/*
|--------------------------------------------------------------------------
| Temporary Pending Account Password
|--------------------------------------------------------------------------
|
| The admin does not choose the homeowner password.
| A random password is stored while the account is pending.
| The homeowner will set the real password after approval.
|
*/

$temporaryPassword =
    bin2hex(
        random_bytes(32)
    );

$password =
    password_hash(
        $temporaryPassword,
        PASSWORD_DEFAULT
    );

unset(
    $temporaryPassword
);

$status = 'pending';

$conn->begin_transaction();

$stmtHome = $conn->prepare("
    INSERT INTO homeowners
    (
        public_id,

        first_name,
        middle_name,
        last_name,

        contact_number,
        email,
        password,
        must_change_password,

        phase,

        house_lot_number,
        block,
        lot,
        street,

        barangay,
        city_municipality,
        province,
        region,
        zip_code,
        country,

        valid_id_path,
        proof_of_billing_path,

        map_x,
        map_y,

        admin_id,
        status
    )
VALUES
(
    NULL,

    ?,?,?,

    ?,?,?,
    1,

    ?,

    ?,?,?,?,

    ?,?,?,?,?,?,

    ?,?,

    ?,?,

    ?,?
)
");

$stmtHome->bind_param(
    "ssssssssiisssssssssiiis",

    $first_name,
    $middle_name,
    $last_name,

    $contact_number,
    $email,
    $password,

    $phase,

    $house_lot_number,
    $block,
    $lot,
    $street,

    $barangay,
    $city_municipality,
    $province,
    $region,
    $zip_code,
    $country,

    $valid_id_path,
    $proof_path,

    $map_x,
    $map_y,

    $assigned_admin_id,
    $status
);

$stmtHome->execute();

$homeowner_id =
    (int)$stmtHome->insert_id;

$stmtHome->close();


/*
|--------------------------------------------------------------------------
| Generate Public Homeowner ID
|--------------------------------------------------------------------------
|
| Public ID now uses the actual database homeowner ID.
|
| Examples:
|
| homeowner id 25 + Phase 1 = P125
| homeowner id 26 + Phase 2 = P226
| homeowner id 27 + Phase 3 = P327
|
*/

$phaseNumber =
    (int)filter_var(
        $phase,
        FILTER_SANITIZE_NUMBER_INT
    );


if (
    $phaseNumber < 1 ||
    $phaseNumber > 3
) {

    throw new RuntimeException(
        'Unable to generate homeowner public ID.'
    );
}


$public_id =
    'P' .
    $phaseNumber .
    $homeowner_id;


$stmtPublicId =
    $conn->prepare("
        UPDATE homeowners
        SET public_id=?
        WHERE id=?
        LIMIT 1
    ");


$stmtPublicId->bind_param(
    "si",
    $public_id,
    $homeowner_id
);


$stmtPublicId->execute();


if ($stmtPublicId->affected_rows !== 1) {

    $stmtPublicId->close();

    throw new RuntimeException(
        'Failed to generate homeowner public ID.'
    );
}


$stmtPublicId->close();


if (
    isset($_POST['member_first_name']) &&
    is_array($_POST['member_first_name'])
) {
      $stmtMember = $conn->prepare("
        INSERT INTO household_members
        (homeowner_id, first_name, middle_name, last_name, relation)
        VALUES (?,?,?,?,?)
      ");

      foreach ($_POST['member_first_name'] as $i => $mfname) {
        $mfname   = trim((string)$mfname);
        $mmname   = trim((string)($_POST['member_middle_name'][$i] ?? ''));
        $mlname   = trim((string)($_POST['member_last_name'][$i] ?? ''));
        $relation = trim((string)($_POST['member_relation'][$i] ?? ''));

        $allowedRelations = ['Homeowner','Spouse','Child','Parent','Relative','Tenant','Caretaker'];if ($mfname === '' && $mlname === '' && $relation === '') {
          continue;
        }

        if ($mfname === '' || $mlname === '' || !in_array($relation, $allowedRelations, true)) {
          throw new Exception('One or more household members have incomplete or invalid details.');
        }

        $stmtMember->bind_param("issss", $homeowner_id, $mfname, $mmname, $mlname, $relation);
        $stmtMember->execute();
      }

      $stmtMember->close();
    }

    $conn->commit();

    if ($possibleTransferOwner && otEmailsDifferent(
        ['email' => $email],
        $possibleTransferOwner
    )) {
        $oldOwnerName = otFullName($possibleTransferOwner);
        logHomeownerActivity(
            $conn,
            'Possible ownership transfer detected',
            "Pending homeowner {$public_id} - {$first_name} {$last_name} was registered for {$phase}, Block {$block}, Lot {$lot}, which is currently assigned to {$oldOwnerName} (#" . (int)$possibleTransferOwner['id'] . "). Ownership-transfer verification is required before approval.",
            $admin_id,
            $phase
        );

        $_SESSION['flash_type'] = 'warning';
        $_SESSION['flash_message'] =
            'Registration saved as Pending. This Block and Lot already has an active homeowner, so the record was flagged as a Possible Ownership Transfer. Review both homeowners in Household Approval and complete transfer verification before activating the new owner.';
    } else {
        logHomeownerActivity(
            $conn,
            'Homeowner registered for review',
            "Pending homeowner {$public_id} - {$first_name} {$last_name} was registered for {$phase}, Block {$block}, Lot {$lot}.",
            $admin_id,
            $phase
        );
        $_SESSION['flash_type'] = 'success';
        $_SESSION['flash_message'] = 'Done Registering.';
    }

    header("Location: ho_approval.php");
    exit;

  } catch (Throwable $e) {
    try { $conn->rollback(); } catch (Throwable $ignored) {}

    $msg = $e->getMessage();

    if (stripos($msg, 'Duplicate entry') !== false && stripos($msg, 'uniq_homeowner_email') !== false) {
      $msg = 'Email already exists.';
    }

    redirect_with_message('danger', $msg);
  }
}

// ---- STEP 1: Registration submit (upload documents, then show map) ----
$showMap = isset($_POST['registration_submit']) && !isset($_POST['submit_location']);

$valid_id_tmp = '';
$proof_tmp = '';

if ($showMap) {
  try {

    /*
|--------------------------------------------------------------------------
| Secure document uploads
|--------------------------------------------------------------------------
*/

$valid_id_tmp = '';
$proof_tmp = '';


try {

    $valid_id_tmp =
        saveRegistrationDocument(
            $_FILES['valid_id'] ?? [],
            'id'
        );


    $proof_tmp =
        saveRegistrationDocument(
            $_FILES['proof_of_billing'] ?? [],
            'proof'
        );


} catch (Throwable $uploadError) {

    /*
     * If Valid ID was already saved
     * but Proof of Billing failed,
     * remove the first uploaded file.
     */
    if ($valid_id_tmp !== '') {

        $validFsPath =
            dirname(__DIR__) .
            DIRECTORY_SEPARATOR .
            str_replace(
                '/',
                DIRECTORY_SEPARATOR,
                $valid_id_tmp
            );


        if (is_file($validFsPath)) {

            @unlink(
                $validFsPath
            );
        }
    }


    throw $uploadError;
}

  } catch (Throwable $e) {
    redirect_with_message('danger', $e->getMessage());
  }
}
?>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>HOA-ADMIN</title>

	<link rel="apple-touch-icon" sizes="180x180" href="vendors/images/apple-touch-icon.png">
	<link rel="icon" type="image/png" sizes="32x32" href="vendors/images/favicon-32x32.png">
	<link rel="icon" type="image/png" sizes="16x16" href="vendors/images/favicon-16x16.png">

	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

	<link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="vendors/styles/core.css">
	<link rel="stylesheet" type="text/css" href="vendors/styles/icon-font.min.css">
	<link rel="stylesheet" type="text/css" href="src/plugins/datatables/css/dataTables.bootstrap4.min.css">
	<link rel="stylesheet" type="text/css" href="src/plugins/datatables/css/responsive.bootstrap4.min.css">
	<link rel="stylesheet" type="text/css" href="vendors/styles/style.css">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="vendors/styles/style.css">
	<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

	<link rel="stylesheet" href="https://cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css">
	<script async src="https://www.googletagmanager.com/gtag/js?id=UA-119386393-1"></script>

	

	<style>
		:root{--brand:#077f46;}
		.card-box{border-radius:14px}
		.page-title-wrap{display:flex;align-items:center;justify-content:center;text-align:center;margin-bottom:14px}
		.page-title-wrap .subtitle{font-size:14px}
		.step-pill{display:inline-flex;gap:8px;align-items:center;padding:6px 10px;border-radius:999px;border:1px solid #e5e7eb;background:#f8fafc;font-weight:800;font-size:12px}

		.access-toast {
		  position: fixed;
		  top: 20px;
		  right: 20px;
		  background: #ef4444;
		  color: #fff;
		  padding: 12px 18px;
		  border-radius: 8px;
		  font-weight: 600;
		  box-shadow: 0 6px 18px rgba(0,0,0,0.2);
		  z-index: 99999;
		  opacity: 0;
		  transform: translateY(-10px);
		  transition: all .3s ease;
		}

		.access-toast.show {
		  opacity: 1;
		  transform: translateY(0);
		}
	</style>
</head>

<body>

	<div class="header">
		<div class="header-left">
			<div class="menu-icon dw dw-menu"></div>
			<div class="search-toggle-icon dw dw-search2" data-toggle="header_search"></div>
		</div>
		<div class="header-right">
			<div class="user-info-dropdown">
				<div class="dropdown">
					<a class="dropdown-toggle" href="#" role="button" data-toggle="dropdown">
						<span class="user-icon">
							<img src="vendors/images/photo1.jpg" alt="">
						</span>
					</a>
					<div class="dropdown-menu dropdown-menu-right dropdown-menu-icon-list">
						<a class="dropdown-item" href="logout.php"><i class="dw dw-logout"></i> Log Out</a>
					</div>
				</div>
			</div>
		</div>
	</div>

	<?php include 'sidebar.php'; ?>
	<div class="mobile-menu-overlay"></div>

	<div class="main-container">
		<div class="pd-ltr-20">

			<div class="page-title-wrap">
				<div>
					<h2 class="h4 mb-1">Home Owner Management</h2>
					<div class="text-muted fw-semibold subtitle">Register Household</div>
				</div>
			</div>

			<div class="card-box p-3">

				<?php if (!empty($_SESSION['flash_message'])): ?>
					<div class="alert alert-<?= esc($_SESSION['flash_type'] ?? 'info') ?> alert-dismissible fade show" role="alert">
						<?= esc($_SESSION['flash_message']) ?>
						<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
					</div>
					<?php unset($_SESSION['flash_type'], $_SESSION['flash_message']); ?>
				<?php endif; ?>

				<?php if (!$showMap): ?>
					<div class="d-flex justify-content-end mb-2">
						<span class="step-pill">✅ Step 1: Details</span>
					</div>

					<form method="POST" enctype="multipart/form-data" id="registrationForm">
						<h5 class="mb-3 border-bottom pb-2">Homeowner Information</h5>

						<div class="row g-3 mb-4">
							<div class="col-md-4">
								<label class="form-label fw-semibold">First Name</label>
								<input type="text" name="first_name" class="form-control" required>
							</div>
							<div class="col-md-4">
								<label class="form-label fw-semibold">Middle Name</label>
								<input type="text" name="middle_name" class="form-control">
							</div>
							<div class="col-md-4">
								<label class="form-label fw-semibold">Last Name</label>
								<input type="text" name="last_name" class="form-control" required>
							</div>
						</div>

						<div class="row g-3 mb-4">
							<div class="col-md-6">
								<label class="form-label fw-semibold">Contact Number</label>
								<input type="tel" name="contact_number" class="form-control" required>
							</div>
							<div class="col-md-6">
								<label class="form-label fw-semibold">Email Address</label>
								<input type="email" name="email" class="form-control" required>
							</div>
						</div>


<div class="row g-3 mb-4">

    <div class="col-md-4">

        <label class="form-label fw-semibold">
            Phase
        </label>

        <?php if ($admin_role === 'superadmin'): ?>

            <select
                name="phase"
                class="form-select"
                required
            >
                <option
                    value=""
                    disabled
                    selected
                >
                    Select Phase
                </option>

                <option value="Phase 1">
                    Phase 1
                </option>

                <option value="Phase 2">
                    Phase 2
                </option>

                <option value="Phase 3">
                    Phase 3
                </option>

            </select>

        <?php else: ?>

            <input
                type="text"
                class="form-control"
                value="<?= esc($admin_phase) ?>"
                readonly
            >

            <input
                type="hidden"
                name="phase"
                value="<?= esc($admin_phase) ?>"
            >

        <?php endif; ?>

    </div>


    <div class="col-md-4">

        <label class="form-label fw-semibold">
            Block
        </label>

        <select
            name="block"
            id="registerBlock"
            class="form-select"
            required
        >

            <option value="">
                Select Block
            </option>

        </select>

    </div>


    <div class="col-md-4">

        <label class="form-label fw-semibold">
            Lot
        </label>

        <select
            name="lot"
            id="registerLot"
            class="form-select"
            required
            disabled
        >

            <option value="">
                Select Block First
            </option>

        </select>

    </div>


    <div class="col-12">

        <div
            id="selectedPropertyInfo"
            class="alert alert-light border mb-0"
        >

            Select a Block and Lot to view the
            official South Meridian property location.

        </div>

    </div>

</div>

						<h5 class="mt-4 mb-3 border-bottom pb-2">Required Documents</h5>
						<div class="row g-4 mb-4">
							<div class="col-md-6">
								<label class="form-label fw-semibold">Valid ID</label>
								<input
    type="file"
    name="valid_id"
    class="form-control"
    accept=".jpg,.jpeg,.png,.pdf"
    required
>
							</div>
							<div class="col-md-6">
								<label class="form-label fw-semibold">Proof of Billing</label>
								<input
    type="file"
    name="proof_of_billing"
    class="form-control"
    accept=".jpg,.jpeg,.png,.pdf"
    required
>
							</div>
						</div>

						<h5 class="mt-4 mb-3 border-bottom pb-2">Household Members</h5>
						<div id="members">
							<div class="member border rounded-3 p-3 mb-3 bg-white">
								<div class="row g-3 align-items-end">
									<div class="col-md-4">
										<input type="text" name="member_first_name[]" class="form-control" placeholder="First Name" required>
									</div>
									<div class="col-md-3">
										<input type="text" name="member_middle_name[]" class="form-control" placeholder="Middle Name">
									</div>
									<div class="col-md-3">
										<input type="text" name="member_last_name[]" class="form-control" placeholder="Last Name" required>
									</div>
									<div class="col-md-2">
										<select name="member_relation[]" class="form-control" required>
											<option value="" disabled selected>Relation</option>
											<option value="Homeowner">Homeowner</option>
											<option value="Spouse">Spouse</option>
											<option value="Child">Child</option>
											<option value="Parent">Parent</option>
											<option value="Relative">Relative</option>
											<option value="Tenant">Tenant</option>
											<option value="Caretaker">Caretaker</option>
										</select>
									</div>
								</div>
							</div>
						</div>

						<button type="button" class="btn btn-outline-success mb-3" onclick="addMember()">+ Add Member</button>

						<div class="d-flex justify-content-end">
<button
    type="submit"
    name="registration_submit"
    class="btn btn-success px-4"
>
    Next: Confirm Location
</button>
						</div>
					</form>

<?php else: ?>

    <?php

    $stepBlock =
        (int)(
            $_POST['block'] ?? 0
        );

    $stepLot =
        (int)(
            $_POST['lot'] ?? 0
        );


    $stepLocationKey =
        $stepBlock .
        ':' .
        $stepLot;


    $stepLocation =
        $southMeridianLocations[
            $stepLocationKey
        ]
        ?? null;


    if (!$stepLocation) {

        redirect_with_message(
            'danger',
            'The selected Block and Lot could not be found on the official South Meridian map.'
        );
    }


    $stepMapX =
        (int)$stepLocation['map_x'];

    $stepMapY =
        (int)$stepLocation['map_y'];

    $stepStreet =
        trim(
            (string)(
                $stepLocation['street'] ?? ''
            )
        );


    $markerLeft =
        ($stepMapX / 2550) * 100;

    $markerTop =
        ($stepMapY / 3300) * 100;

    ?>


    <div class="d-flex justify-content-between align-items-center mb-3">

        <span class="step-pill">
            ✅ Step 1: Details
        </span>

        <span class="step-pill">
            📍 Step 2: Confirm Location
        </span>

    </div>


    <form method="POST">

        <h5 class="mb-3 border-bottom pb-2 text-success">
            Confirm Property Location
        </h5>


        <?php

        /*
         * Carry Step 1 fields to final submission.
         */
        $skipHiddenFields = [
            'registration_submit'
        ];


        foreach (
            $_POST as
            $key =>
            $value
        ) {

            if (
                in_array(
                    $key,
                    $skipHiddenFields,
                    true
                )
            ) {
                continue;
            }


            if (is_array($value)) {

                foreach (
                    $value as
                    $v
                ) {

                    echo
                        '<input type="hidden" name="' .
                        esc($key) .
                        '[]" value="' .
                        esc($v) .
                        '">';
                }

            } else {

                echo
                    '<input type="hidden" name="' .
                    esc($key) .
                    '" value="' .
                    esc($value) .
                    '">';
            }
        }

        ?>


        <input
            type="hidden"
            name="valid_id_tmp"
            value="<?= esc($valid_id_tmp) ?>"
        >

        <input
            type="hidden"
            name="proof_tmp"
            value="<?= esc($proof_tmp) ?>"
        >


        <div class="alert alert-success">

            <strong>
                Selected Property
            </strong>

            <br>

            Phase:
            <?= esc(
                $admin_role === 'superadmin'
                    ? ($_POST['phase'] ?? '')
                    : $admin_phase
            ) ?>

            <br>

            Block:
            <?= (int)$stepBlock ?>

            <br>

            Lot:
            <?= (int)$stepLot ?>

            <?php if ($stepStreet !== ''): ?>

                <br>

                Street:
                <?= esc($stepStreet) ?>

            <?php endif; ?>

        </div>


        <div
            style="
                position:relative;
                width:100%;
                max-width:850px;
                margin:0 auto;
                overflow:hidden;
                border:2px solid var(--brand);
                border-radius:14px;
                background:#f3f4f6;
            "
        >

            <img
                src="../assets/img/south_meridian_block_lot_map.png"
                alt="South Meridian Block and Lot Map"
                style="
                    display:block;
                    width:100%;
                    height:auto;
                "
            >


            <div
                title="Block <?= (int)$stepBlock ?>, Lot <?= (int)$stepLot ?>"
                style="
                    position:absolute;

                    left:
                        <?= esc(
                            number_format(
                                $markerLeft,
                                4,
                                '.',
                                ''
                            )
                        ) ?>%;

                    top:
                        <?= esc(
                            number_format(
                                $markerTop,
                                4,
                                '.',
                                ''
                            )
                        ) ?>%;

                    transform:
                        translate(-50%, -100%);

                    font-size:30px;

                    color:#dc3545;

                    text-shadow:
                        0 1px 4px rgba(0,0,0,.45);

                    z-index:5;
                "
            >
                📍
            </div>

        </div>


        <div class="text-center mt-2 text-muted">

            Block <?= (int)$stepBlock ?>,
            Lot <?= (int)$stepLot ?>

            <?php if ($stepStreet !== ''): ?>

                · <?= esc($stepStreet) ?>

            <?php endif; ?>

        </div>


        <button
            type="submit"
            name="submit_location"
            class="btn btn-success w-100 mt-3"
        >
            Confirm &amp; Submit Registration
        </button>

    </form>

<?php endif; ?>

			</div>

			<div class="footer-wrap pd-20 mb-20 card-box">
				© Copyright South Meridian Homes All Rights Reserved
			</div>
		</div>
	</div>

	<script src="vendors/scripts/core.js"></script>
	<script src="vendors/scripts/script.min.js"></script>
	<script src="vendors/scripts/process.js"></script>
	<script src="vendors/scripts/layout-settings.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>

	<script>
		function addMember() {
			const members = document.getElementById('members');
			const member = members.firstElementChild.cloneNode(true);
			member.querySelectorAll('input').forEach(input => input.value = '');
			member.querySelectorAll('select').forEach(select => select.selectedIndex = 0);
			members.appendChild(member);
		}
	</script>

	<div id="accessToast" class="access-toast">
	  🚫 You do not have access to that part.
	</div>

	<script>
	window.userPermissions = <?= json_encode($permissions, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES) ?>;

	document.addEventListener('DOMContentLoaded', function () {
	  const toast = document.getElementById('accessToast');

	  function showAccessToast() {
	    toast.classList.add('show');
	    setTimeout(() => {
	      toast.classList.remove('show');
	    }, 2500);
	  }

	  document.querySelectorAll('.menu-access-link').forEach(function(link){
	    link.addEventListener('click', function(e){
	      const moduleKey = this.dataset.module || '';
	      const allowed = !!window.userPermissions[moduleKey];

	      if(!allowed){
	        e.preventDefault();
	        showAccessToast();
	      }
	    });
	  });
	});
	</script>

	<script>
const registerLocations =
    <?= json_encode(
        array_values($southMeridianLocations),
        JSON_UNESCAPED_UNICODE |
        JSON_UNESCAPED_SLASHES
    ) ?>;


document.addEventListener(
    'DOMContentLoaded',
    function () {

        const blockSelect =
            document.getElementById(
                'registerBlock'
            );

        const lotSelect =
            document.getElementById(
                'registerLot'
            );

        const propertyInfo =
            document.getElementById(
                'selectedPropertyInfo'
            );


        if (
            !blockSelect ||
            !lotSelect
        ) {
            return;
        }


        /*
        |--------------------------------------------------------------------------
        | Build Block list
        |--------------------------------------------------------------------------
        */

        const blocks =
            [
                ...new Set(
                    registerLocations.map(
                        item =>
                            Number(
                                item.block
                            )
                    )
                )
            ]
            .filter(
                Number.isFinite
            )
            .sort(
                (a, b) =>
                    a - b
            );


        blocks.forEach(
            block => {

                const option =
                    document.createElement(
                        'option'
                    );

                option.value =
                    block;

                option.textContent =
                    'Block ' + block;

                blockSelect.appendChild(
                    option
                );
            }
        );


        /*
        |--------------------------------------------------------------------------
        | Block changed
        |--------------------------------------------------------------------------
        */

        blockSelect.addEventListener(
            'change',
            function () {

                const block =
                    Number(
                        this.value
                    );


                lotSelect.innerHTML =
                    '<option value="">Select Lot</option>';


                propertyInfo.innerHTML =
                    'Select a Lot.';


                if (!block) {

                    lotSelect.disabled =
                        true;

                    return;
                }


                const lots =
                    registerLocations
                        .filter(
                            item =>
                                Number(
                                    item.block
                                ) === block
                        )
                        .sort(
                            (a, b) =>
                                Number(a.lot) -
                                Number(b.lot)
                        );


                lots.forEach(
                    item => {

                        const option =
                            document.createElement(
                                'option'
                            );

                        option.value =
                            item.lot;

                        option.textContent =
                            'Lot ' +
                            item.lot;

                        lotSelect.appendChild(
                            option
                        );
                    }
                );


                lotSelect.disabled =
                    false;
            }
        );


        /*
        |--------------------------------------------------------------------------
        | Lot changed
        |--------------------------------------------------------------------------
        */

        lotSelect.addEventListener(
            'change',
            function () {

                const block =
                    Number(
                        blockSelect.value
                    );

                const lot =
                    Number(
                        lotSelect.value
                    );


                const location =
                    registerLocations.find(
                        item =>
                            Number(
                                item.block
                            ) === block
                            &&
                            Number(
                                item.lot
                            ) === lot
                    );


                if (!location) {

                    propertyInfo.innerHTML =
                        'Select a valid property.';

                    return;
                }


                propertyInfo.innerHTML =
                    '<strong>Selected Property:</strong> ' +
                    'Block ' +
                    block +
                    ', Lot ' +
                    lot +
                    (
                        location.street
                            ? ' · ' +
                              location.street
                            : ''
                    );
            }
        );

    }
);
</script>
</body>
</html>