<?php

header('Referrer-Policy: no-referrer');

header('X-Content-Type-Options: nosniff');

session_start();

if (empty($_SESSION['reset_password_csrf'])) {
    $_SESSION['reset_password_csrf'] =
        bin2hex(
            random_bytes(32)
        );
}

$resetPasswordCsrf =
    $_SESSION['reset_password_csrf'];

require_once '../config/database.php';


function esc($v): string
{
    return htmlspecialchars(
        (string)$v,
        ENT_QUOTES,
        'UTF-8'
    );
}


/*
|--------------------------------------------------------------------------
| Page state
|--------------------------------------------------------------------------
*/

$pageError =
    '';

$successMsg =
    '';

$errorMsg =
    '';

$user =
    null;

$tokenHash =
    '';


/*
|--------------------------------------------------------------------------
| Read and validate token
|--------------------------------------------------------------------------
*/

$token =
    strtolower(
        trim(
            (string)(
                $_GET['token'] ?? ''
            )
        )
    );


/*
 * Token generated by bin2hex(random_bytes(32))
 * must be exactly 64 hexadecimal characters.
 *
 * Do not remove arbitrary characters from the token.
 */
if (
    !preg_match(
        '/\A[a-f0-9]{64}\z/',
        $token
    )
) {

    $pageError =
        'Invalid or missing token.';

} else {

    /*
     * The database contains only the SHA-256 hash.
     */
    $tokenHash =
        hash(
            'sha256',
            $token
        );


    /*
    |--------------------------------------------------------------------------
    | Find approved homeowner using hashed token
    |--------------------------------------------------------------------------
    */

    $stmt =
        $conn->prepare("
            SELECT
                id,
                reset_expires
            FROM homeowners
            WHERE reset_token = ?
              AND status = 'approved'
              AND must_change_password = 1
            LIMIT 1
        ");


    $stmt->bind_param(
        's',
        $tokenHash
    );


    $stmt->execute();


    $user =
        $stmt
            ->get_result()
            ->fetch_assoc();


    $stmt->close();


    /*
    |--------------------------------------------------------------------------
    | Validate token expiration
    |--------------------------------------------------------------------------
    */

    if (!$user) {

        $pageError =
            'Invalid or expired token.';

    } else {

        $expires =
            $user['reset_expires']
            ?? null;


        if (
            !$expires ||
            strtotime(
                (string)$expires
            ) <= time()
        ) {

            $pageError =
                'Invalid or expired token.';
        }
    }
}


/*
|--------------------------------------------------------------------------
| Password submission
|--------------------------------------------------------------------------
*/

if (
    empty($pageError) &&
    $_SERVER['REQUEST_METHOD'] === 'POST'
) {

    $submittedCsrf =
        (string)(
            $_POST['csrf'] ?? ''
        );

    if (
        $submittedCsrf === '' ||
        !hash_equals(
            $resetPasswordCsrf,
            $submittedCsrf
        )
    ) {

        $errorMsg =
            'Security token expired. Reload the page and try again.';

    } else {

    $pass =
        (string)(
            $_POST['password'] ?? ''
        );

    $pass2 =
        (string)(
            $_POST['password2'] ?? ''
        );


    /*
    |--------------------------------------------------------------------------
    | Password validation
    |--------------------------------------------------------------------------
    */

    if (
        strlen($pass) < 8
    ) {

        $errorMsg =
            'Password must be at least 8 characters.';

    } elseif (
        $pass !== $pass2
    ) {

        $errorMsg =
            'Passwords do not match.';

    } else {

        $hash =
            password_hash(
                $pass,
                PASSWORD_DEFAULT
            );


        $homeownerId =
            (int)(
                $user['id']
                ?? 0
            );


        /*
         * Use PHP's current time because reset_expires was
         * also created using PHP date().
         */
        $now =
            date(
                'Y-m-d H:i:s'
            );


        /*
        |--------------------------------------------------------------------------
        | Atomic one-time token update
        |--------------------------------------------------------------------------
        |
        | The update succeeds only when:
        |
        | - homeowner still exists
        | - token still matches
        | - token has not expired
        | - homeowner is approved
        | - password setup is still required
        |
        | Because reset_token becomes NULL here, the same link
        | cannot successfully be used again.
        |
        */

        $stmt =
            $conn->prepare("
                UPDATE homeowners
                SET
                    password = ?,
                    must_change_password = 0,
                    reset_token = NULL,
                    reset_expires = NULL
                WHERE id = ?
                  AND reset_token = ?
                  AND reset_expires > ?
                  AND status = 'approved'
                  AND must_change_password = 1
                LIMIT 1
            ");


        $stmt->bind_param(
            'siss',
            $hash,
            $homeownerId,
            $tokenHash,
            $now
        );


        $stmt->execute();


        $updated =
            $stmt->affected_rows;


        $stmt->close();


        if (
            $updated !== 1
        ) {

            $errorMsg =
                'This password setup link is invalid or expired.';

} else {

    $successMsg =
        'Password set successfully. You may now login.';

    unset(
        $_SESSION['reset_password_csrf']
    );
}
    }
  }
}
?>
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Set Password • South Meridian HOA</title>

  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

  <!-- Match your dashboard theme -->
  <link rel="stylesheet" type="text/css" href="vendors/styles/core.css">
  <link rel="stylesheet" type="text/css" href="vendors/styles/icon-font.min.css">
  <link rel="stylesheet" type="text/css" href="vendors/styles/style.css">

  <style>
    body {
    background: #f4f6f8;
    font-family:
        -apple-system,
        BlinkMacSystemFont,
        "Segoe UI",
        Arial,
        sans-serif;
}
    .auth-wrap {
      min-height: 100vh;
      display: flex;
      align-items: center;
      justify-content: center;
      padding: 24px;
    }
    .auth-card {
      width: min(560px, 96vw);
      border-radius: 16px;
      overflow: hidden;
    }
    .auth-head {
      background: #077f46;
      color: #fff;
      padding: 18px 20px;
      display: flex;
      align-items: center;
      justify-content: space-between;
      gap: 12px;
    }
    .auth-title {
      margin: 0;
      font-weight: 900;
      font-size: 18px;
      letter-spacing: .2px;
    }
    .auth-sub {
      margin: 2px 0 0;
      opacity: .9;
      font-size: 12px;
      font-weight: 600;
    }
    .auth-body { padding: 20px; }
    .form-group label { font-weight: 800; }
    .btn-green {
      background:#077f46;
      border-color:#077f46;
      color:#fff;
      font-weight: 800;
      border-radius: 10px;
      padding: 10px 14px;
    }
    .btn-green:hover { filter: brightness(.95); color:#fff; }
    .mini {
      font-size: 12px;
      color: #64748b;
      font-weight: 600;
    }
    .divider {
      height: 1px;
      background: #e5e7eb;
      margin: 16px 0;
    }
  </style>
</head>

<body>

<div class="auth-wrap">
  <div class="card-box auth-card">
    <div class="auth-head">
      <div>
        <h1 class="auth-title">Set Your Password</h1>
        <div class="auth-sub">South Meridian HOA • Homeowner Account</div>
      </div>
      <div style="font-size:22px; opacity:.95;">
        <i class="dw dw-lock"></i>
      </div>
    </div>

    <div class="auth-body">

      <?php if (!empty($pageError)): ?>
        <div class="alert alert-danger" role="alert" style="border-radius:12px;">
          <b>Oops!</b> <?= esc($pageError) ?>
          <div class="mt-2 mini">
            Tip: If you clicked an old email, request approval again or ask admin to resend the link.
          </div>
        </div>

        <div class="divider"></div>
        <a href="../index.php" class="btn btn-outline-secondary btn-block" style="border-radius:10px;font-weight:800;">
          Back to Login
        </a>

      <?php elseif ($successMsg): ?>
        <div class="alert alert-success" role="alert" style="border-radius:12px;">
          <b>Success!</b> <?= esc($successMsg) ?>
        </div>

        <div class="divider"></div>
        <a href="../index.php" class="btn btn-green btn-block">
          Go to Login
        </a>

      <?php else: ?>
        <?php if ($errorMsg): ?>
          <div class="alert alert-danger" role="alert" style="border-radius:12px;">
            <?= esc($errorMsg) ?>
          </div>
        <?php endif; ?>

        <div class="mini mb-2">
          Create a strong password (min. 8 characters). This link expires automatically.
        </div>

        <form method="POST" autocomplete="off">
          <input
    type="hidden"
    name="csrf"
    value="<?= esc($resetPasswordCsrf) ?>"
>
          <div class="form-group">
            <label>New Password</label>
            <div class="input-group">
              <input type="password" class="form-control" name="password" required minlength="8" placeholder="Enter new password">
              <div class="input-group-append">
                <span class="input-group-text"><i class="dw dw-padlock"></i></span>
              </div>
            </div>
          </div>

          <div class="form-group">
            <label>Confirm Password</label>
            <div class="input-group">
              <input type="password" class="form-control" name="password2" required minlength="8" placeholder="Confirm new password">
              <div class="input-group-append">
                <span class="input-group-text"><i class="dw dw-padlock1"></i></span>
              </div>
            </div>
          </div>

          <button type="submit" class="btn btn-green btn-block">
            Set Password
          </button>

          <div class="text-center mt-3 mini">
            Having trouble? Contact your HOA admin for a new link.
          </div>
        </form>
      <?php endif; ?>

    </div>
  </div>
</div>

</body>
</html>